# refmet_map ----
#' TBA
#'
#' The refmet_map function.
#'
#' @param thefile A file name
#'
#' @return A data frame
#'
#' @export
#'
#' @examples
#' library(RefMet)
#' infile <- system.file("extdata", "met_list.txt", package = "RefMet")
#' #Use a text file of metabolite names as input
#' RefMet_mapped <- refmet_map(infile)
#' head(RefMet_mapped)
#'
refmet_map <- function(thefile){
DF <- read.table(thefile, header = TRUE, na.strings = "-", stringsAsFactors = FALSE, quote = "", comment.char = "", sep="\t");
mets=stri_join_list(list(DF[,1]), sep="\n")
h <- new_handle()
handle_setform(h,  metabolite_name = mets)
#run the RefMet request on the Metabolomics Workbench server
req <- curl_fetch_memory("https://www.metabolomicsworkbench.org/databases/refmet/name_to_refmet_new_min.php", handle = h)
refmet <- read.table(text = rawToChar(req$content), header = TRUE, na.strings = "-", stringsAsFactors = FALSE, quote = "", comment.char = "", sep="\t");
refmet[is.na(refmet)] <- '-'
refmet[refmet==''] <- '-'
refmet
}

# refmet_map_df ----
#' Grab mass-spectrometry data from file(s)
#'
#' The refmet_map_df function.
#'
#' @param DX (a data frame column with metabolite names
#'
#' @return A data frame  (rt),
#'
#' @export
#'
#' @examples
#' library(RefMet)
#' 
#' DF <- read.table(thefile, header = TRUE,  quote = "", sep="\t");
#' #Use a data frame column as input
#' RefMet_mapped <- refmet_map_df(DF[,1])
#' head(RefMet_mapped)
#'
refmet_map_df <- function(DX){
mets=stri_join_list(list(DX), sep="\n")
h <- new_handle()
handle_setform(h,  metabolite_name = mets)
#run the RefMet request on the Metabolomics Workbench server
req <- curl_fetch_memory("https://www.metabolomicsworkbench.org/databases/refmet/name_to_refmet_new_min.php", handle = h)
refmet <- read.table(text = rawToChar(req$content), header = TRUE, na.strings = "-", stringsAsFactors = FALSE, quote = "", comment.char = "", sep="\t");
refmet[is.na(refmet)] <- '-'
refmet[refmet==''] <- '-'
refmet
}

# refmet_metadata ----
#' TBA
#'
#' The refmet_map function.
#'
#' @param metabolite A metabolite name
#'
#' @return A data frame
#'
#' @export
#'
#' @examples
#' library(RefMet)
#' 
#' metadata<- refmet_metadata("Tyrosine")
#' head(metadata)
#'
refmet_metadata <- function(metabolite){
metabolite_enc <- URLencode(metabolite)
myurl <-paste0("http://dev.metabolomicsworkbench.org:45076/data/metstatR.php?REFMET_NAME=",metabolite_enc)
h <- new_handle()
handle_setopt(
    handle = h,
    httpauth = 1,
    userpwd = "DRCC:mw@UC13"
)
req <- curl_fetch_memory(myurl, handle = h)
metadata <- read.table(text = rawToChar(req$content), header = TRUE, na.strings = "-", stringsAsFactors = FALSE, quote = "", comment.char = "", sep="\t");
metadata
}

# adduct_calc ----
#' TBA
#'
#' The adduct_calc function.
#'
#' @param myadduct An adduct name , e.g. '[M+H]+' or '[M-H]-'
#' Complete list: [M+H]+ [M+Na]+ [M+NH4]+ [M+H-H2O]+ [M+2H]2+ [M+3H]3+ [M+4H]4+ 
#' [M+K]+ [M+2K]2+ [M+2Na]2+ [M+2Na-H]+ [M+2K-H]+ [M+Ag]+ [M+Li]+ 
#' [M+2Li]2+ [M+H+CH3CN]+ [M+Na+CH3CN]+ [M.NaFormate+H]+ [M.NH4Formate+H]+ 
#' [M-H]- [M-H-H2O]- [M-CH3]- [M-2H]2- [M-3H]3- [M-4H]4- [M.Cl]- [M.OAc]- 
#' [M+Na-2H]- [M+K-2H]- [M.Formate]- [M.NaFormate-H]- [M.NH4Formate-H]- 
#' [M.F]- [M.HF2]2- 
#'
#' @param DF The data frame generated by RefMet mapping, e.g. RefMet_mapped
#' The DF must contain the neutral mass column labeled 'Exact.mass'
#'
#' @return A data frame
#'
#' @export
#'
#' @examples
#' library(RefMet)
#' 
#' RefMet_mapped_with_adduct_col<- adduct_calc('[M+H]+',RefMet_mapped)
#' head(RefMet_mapped_with_adduct_col)
#'
adduct_calc <- function(myadduct,DF){
infile <- system.file("extdata", "adducts.txt", package = "RefMet")
adducts <- read.table(infile, header = TRUE, sep="\t");
myrow=subset(adducts,adduct==myadduct)
DF$Exact.mass[DF$Exact.mass == '-'] <- NA
DF$Exact.mass <-as.numeric(DF$Exact.mass)
adduct_col <-(DF$Exact.mass +myrow$mass)/myrow$charge
DF_with_adduct <- cbind(DF,adduct_col)
colnames(DF_with_adduct)[ncol(DF_with_adduct)] <- myadduct
DF_with_adduct
}

# Import area ----

#' @import curl
#' @import stringi
#' @import ggplot2
#' @export
NULL
